# Initial buffer time budget.
BUFFER_TIME_BUDGET: 0
# The number of ticks to delay when agent decides not to assign VM.
DELAY_DURATION: 1

# Path of the vm table data.
VM_TABLE: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vmtable.bin"

# Path of the cpu readings file.
CPU_READINGS: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vm_cpu_readings-file-1-of-195.bin"

PROCESSED_DATA_URL: "https://marodatasource.blob.core.windows.net/vm-scheduling-azure/azure.2019.10k/azure.2019.10k.tar.gz"

# True means kill all VMs on the overload PM.
# False means only count these VMs as failed allocation, but not kill them.
KILL_ALL_VMS_IF_OVERLOAD: True

# Oversubscription configuration.
# Max CPU oversubscription rate.
MAX_CPU_OVERSUBSCRIPTION_RATE: 1.15
# Max memory oversubscription rate.
MAX_MEM_OVERSUBSCRIPTION_RATE: 1
# Max CPU utilization rate.
MAX_UTILIZATION_RATE: 1

components:
  pm:
    - pm_type: 0
      cpu: 32
      memory: 128
      power_curve:
        calibration_parameter: 1.4
        busy_power: 10
        idle_power: 1
    - pm_type: 1
      cpu: 32
      memory: 128
      power_curve:
        calibration_parameter: 1.4
        busy_power: 10
        idle_power: 1
  rack:
    - type: 'JP1-a'
      pm:
        - pm_type: 0
          # NOTE: Is there any way to check if the sum of amount is same as the definition in architecture pm_amount.
          # Or is there any other way to avoid the design like this?
          amount: 50
    - type: 'JP1-b'
      pm:
        - pm_type: 0
          amount: 50
    - type: 'JP2-a'
      pm:
        - pm_type: 1
          amount: 0
    - type: 'JP2-b'
      pm:
        - pm_type: 1
          amount: 0
    - type: 'SK1-a'
      pm:
        - pm_type: 1
          amount: 0
    - type: 'SK1-b'
      pm:
        - pm_type: 1
          amount: 0
    - type: 'FN1-a'
      pm:
        - pm_type: 0
          amount: 0
    - type: 'FN2-a'
      pm:
        - pm_type: 1
          amount: 0
  cluster:
    - type: 'JP1'
      rack:
        - rack_type: 'JP1-a'
        - rack_type: 'JP1-b'
    - type: 'JP2'
      rack:
        - rack_type: 'JP2-a'
        - rack_type: 'JP2-b'
    - type: 'SK1'
      rack:
        - rack_type: 'SK1-a'
        - rack_type: 'SK1-b'
    - type: 'FN1'
      rack:
        - rack_type: 'FN1-a'
    - type: 'FN2'
      rack:
        - rack_type: 'FN2-a'

architecture:
  region:
    - name: 'APAC'
      zone:
        - name: 'asia-northeast1'
          data_center:
            - name: 'Japan'
              cluster:
                - type: 'JP1'
                  rack_amount: 2
                  pm_amount: 100
                - type: 'JP2'
                  rack_amount: 2
                  pm_amount: 0
            - name: 'South Korea'
              cluster:
                - type: 'SK1'
                  rack_amount: 2
                  pm_amount: 0
    - name: 'Europe'
      zone:
        - name: 'europe-north1'
          data_center:
            - name: 'Finland'
              cluster:
                - type: 'FN1'
                  rack_amount: 1
                  pm_amount: 0
                - type: 'FN2'
                  rack_amount: 1
                  pm_amount: 0
